application: fly-viz
version: 1
runtime: go
api_version: go1
threadsafe: yes

handlers:
- url: /
  static_files: home.html
  upload: home.html
  secure: always

- url: /.*
  script: _go_app
  secure: always
